### ISSUE TITLE
Confirm box under comment

### ISSUE THREAD

**Issue by paaljoachim** [belkincapital/wp-qore#3]
Hey

I noticed Confirm text and check box below the Post Comment buttons on each post.
It looked a little misplaced. Should it be there?

**Comment by icryptic** [comment]
Yes, it needs some adjusting probably. Take a peek at line 139 and 140 here. There is some inline css. Yes, I know, that's a bad idea. I have to remove the inline css all together

https://github.com/belkincapital/wp-qore/blob/master/wp-qore.php

**Comment by paaljoachim** [comment]
Clicking the comment confirmation or not makes no difference though as the comment will be posted anyway.
